# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 和县三中2019级11班班史
description: 存放和县三中2019级11班的班史网站
lang: zh-CN
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]

# Regression tests
# By default, the pages in /docs/tests are excluded when the ste is built.
# To include them, comment-out the relevant line above.
# Uncommenting the following line doesn't work - see https://github.com/jekyll/jekyll/issues/4791
# include: ["docs/tests/"]

# Set a path/url to a logo that will be displayed instead of the title
logo: "/logos/logo.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "相册":
    - "//pan.baidu.com/s/15s8uA-303Spla81S8QeBpQ?pwd=ab2b#list/path=%2F"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

remote_theme: just-the-docs/just-the-docs

# title: 和县三中2019级11班班史
# description: 和县三中2019级11班的班史存放网站
# email: 3531148334@qq.com
# lang: zh-CN
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# # Set a path/url to a logo that will be displayed instead of the title
# logo: "/logos/logo.png"

# # Heading anchor links appear on hover over h1-h6 tags in page content
# # allowing users to deep link to a particular heading on a page.
# #
# # Supports true (default) or false
# heading_anchors: true

# # Enable or disable the site search
# # Supports true (default) or false
# search_enabled: false

# # Aux links for the upper right navigation
# aux_links:
#   "相册":
#     - "//pan.baidu.com/s/15s8uA-303Spla81S8QeBpQ?pwd=ab2b#list/path=%2F"

# # Makes Aux links open in a new tab. Default is false
# aux_links_new_tab: true

# # Build settings
# remote_theme: just-the-docs/just-the-docs
