remote_theme: just-the-docs/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
logo: "/logos/logo.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/hxsz2019-11/hxsz2019-11.github.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false